config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  resource :session, only: [:new, :create, :destroy]
  resource :registration, only: [:new, :create]
  resources :authors, only: [:index, :show]
  resources :books, only: [:index, :show] do
    resources :reviews, only: [:create]
  end
  resources :lists, only: [:index, :show]
  resources :genres, only: [:show]
end

app/models/author.rb
class Author < ActiveRecord::Base
  extend FriendlyId
  friendly_id :full_name, use: [:slugged, :finders]

  has_many :books,dependent: :destroy

  validates :full_name, presence: true, uniqueness: true
  validates :gender, presence: true
  validates :born, presence: true

  def popular_books(limit = 5)
    books.limit(limit)
  end
end

app/models/book.rb
class Book < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: [:slugged, :finders]

  NO_REVIEW_SCORE = 0.0

  belongs_to :author
  belongs_to :genre
  has_many :reviews

  validates :title, presence: true
  validates :cover_image, presence: true
  validates :summary, presence: true
  validates :author_id, presence: true
  validates :genre_id, presence: true

  def self.by_genre(genre)
    where("genre_id = ? ", genre)
  end

  def self.lastest_published
    order(created_at: :desc)
  end

  def reviewers
    reviews.map(&:user)
  end

  def average_rating
    if reviews.any?
      reviews.average(:score)
    else
      NO_REVIEW_SCORE
    end
  end
end

app/models/genre.rb
class Genre < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: [:slugged, :finders]
  validates :name, presence: true, uniqueness: true
end

app/models/guest.rb
class Guest
  def authenticate(_)
    false
  end

  def present?
    false
  end
end

app/models/list.rb
class List < ActiveRecord::Base
  has_many :list_entries, class_name: "ListEntry"
  has_many :books, through: :list_entries

  validates :name, presence: true
  validates :name, uniqueness: true

  def ranking_books(limit = 10)
    books.limit(limit)
  end
end

app/models/list_entry.rb
class ListEntry < ActiveRecord::Base
  belongs_to :book
  belongs_to :list

  validates :list_id, presence: true
  validates :book_id, presence: true
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :book

  validates :user_id, :book_id, :content, :score, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :reviews

  validates :email, :name, presence: true
  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @_current_user ||= User.find_by(id: session[:user_id]) || Guest.new
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @authors = Author.all
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @book_service = BookService.new(
      books: Book.page(params[:page])
    )
  end

  def show
    book = Book.includes(:author, :reviews)
      .joins(:author)
      .find(params[:id])

    render locals: {
      book: book,
      reviews: book.reviews,
      review_policy: ReviewPolicy.new(book.reviewers, current_user)
    }
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def show
    @book_service = BookService.new(
      books: Book.by_genre(genre).page(params[:page])
    )
    render template: "books/index"
  end

  private

  def genre
    Genre.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    render locals: {
      genres: Genre.all,
      books: Book.lastest_published.limit(5),
      authors: Author.all
    }
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.
      includes(:books).
      joins(:books).
      where("lists.id = ?", params[:id]).
      first
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to books_path, notice: "Account created successfully"
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    review = Review.new(review_param)
    if review.save
      redirect_to book, notice: "Your review has been creating!"
    else
      redirect_to book, alert: "Something went wrong! :("
    end
  end

  private

  def review_param
    params.require(:review).
      permit(:score, :content).
      merge(book: book, user: current_user)
  end

  def book
    @book ||= Book.find params[:book_id]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    begin
      user = User.find_by_email! email
      if user.authenticate password
        session.update user_id: user.id
        redirect_to books_path, notice: "signed succesfully"
      end
    rescue ActiveRecord::RecordNotFound
      flash.now[:error] = "Invalid email or password."
      render :new
    end
  end

  def destroy
    session.destroy
    redirect_to root_path
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end

  def email
    session_params.fetch(:email)
  end

  def password
    session_params.fetch(:password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def user_signed_in?
    session[:user_id].present?
  end
end

app/helpers/flashes_helper.rb
module FlashesHelper
  def user_facing_flashes
    flash.to_hash.slice("alert", "error", "notice", "success")
  end
end

app/views/application/_analytics.html.erb
<% if ENV["SEGMENT_KEY"] %>
  <script type="text/javascript">
    window.analytics=window.analytics||[],window.analytics.methods=["identify","group","track","page","pageview","alias","ready","on","once","off","trackLink","trackForm","trackClick","trackSubmit"],window.analytics.factory=function(t){return function(){var a=Array.prototype.slice.call(arguments);return a.unshift(t),window.analytics.push(a),window.analytics}};for(var i=0;i<window.analytics.methods.length;i++){var key=window.analytics.methods[i];window.analytics[key]=window.analytics.factory(key)}window.analytics.load=function(t){if(!document.getElementById("analytics-js")){var a=document.createElement("script");a.type="text/javascript",a.id="analytics-js",a.async=!0,a.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.com/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n)}},window.analytics.SNIPPET_VERSION="2.0.9",
    window.analytics.load("<%= ENV["SEGMENT_KEY"] %>");
    window.analytics.page();
  </script>
<% end %>

app/views/application/_flashes.html.erb
<% if flash.any? %>
  <div class="flashes">
    <% user_facing_flashes.each do |key, value| -%>
      <div class="flash-<%= key %>"><%= value %></div>
    <% end -%>
  </div>
<% end %>

app/views/application/_javascript.html.erb
<%= javascript_include_tag :application %>

<%= yield :javascript %>

<%= render "analytics" %>

<% if Rails.env.test? %>
  <%= javascript_tag do %>
    $.fx.off = true;
    $.ajaxSetup({ async: false });
  <% end %>
<% end %>

app/views/authors/index.html.erb
<% @authors.each do |author| %>
  <div class="author__name"><%= link_to(author.full_name, author) %></div>
  <ul class="books books-horizontal">
    <%= render partial: "books/book_preview", collection: author.popular_books, as: :book %>
  </ul>
<% end %>

app/views/authors/show.html.erb
<div class="author-page">
  <div class="author-cover">
    <%= image_tag(@author.picture)%> 
  </div>

  <div class="author-info">
    <div class="author author__name">
      <%= @author.full_name %>
    </div>

    <div class="author author__gender">
      <span>gender:</span>
      <p><%= @author.gender %></p>
    </div>

    <div class="author author__born">
      <span>Born:</span>
      <p><%= @author.born %><p>
    </div>

    <div class="author author__bio">
      <span>About this author:</span>
      <p><%= @author.bio %></p>
    </div>
  </div>

  <ul class="author__books">
    <%= @author.full_name %> books
    <%= render @author.books %>
  </ul>
</div>

app/views/books/_book.html.erb
<li class="book">
  <div class="cover-image">
    <%= image_tag(book.cover_image, width: 128)%>
  </div>
  <div class="book-details">
    <div class="book-title">
      <%= link_to(book.title, book_path(book)) %>
    </div>
    <div class="book-genre">
      <%= book.genre.name %>
    </div>
    <div class="book-summary">
      <%= book.summary %>
    </div>
  </div>
</li>

app/views/books/_book_preview.html.erb
<li class="book book-category">
  <div> 
    <%= link_to book_path(book) do %>
      <% image_tag(book.cover_image, width: 128) %>
    <% end %>
  </div>
</li>

app/views/books/_reviews.html.erb
<div class="reviews">
  <% if review_policy.authorized_for_review? %>
    <%= simple_form_for [book, Review.new] do |f| %>
      <%= f.input :score, collection: 1..5, as: :select, prompt: "**Select score**"%>
      <%= f.input :content, label: "Review" %>
      <%= f.submit "Send review" %>
    <% end %>
  <% elsif !review_policy.has_not_already_reviewer? %>
    <div class="flash-notice">Thanks for review this book!.</div>
  <% else %>
    <div class="flash-notice">
      <%= link_to "log in or sign up for write a review", new_session_path %>
    </div>
  <% end %>
  <h1>Reviews</h1>
  <ul>
    <% reviews.each do |review| %>
      <li class="review">
        <div class="review-image">
          <%= gravatar_image_tag(review.user.email) %>
        </div>
        <div class="review-content">
          <h1>
            <%= review.user.name %> rated at
            <span class="rated-<%= review.score %>"><%= review.score %></span>
          </h1>
          <p><%= review.content %></p>
          <p class="review-detail"></p>
        </div>
      </li>
    <% end %>
  </ul>
</div>

app/views/books/index.html.erb
<div class="filters">
  <ul class="genres">
    <h1>Genres</h1>
    <% @book_service.genres.each do |genre| %>
      <li> <%= link_to(genre.name, genre_path(genre))%> </li>    
    <% end %>
  </ul>
</div>

<ul class="books books-list">
  <%= render @book_service.books %>
</ul>

<%= paginate @book_service.books %>

app/views/books/show.html.erb
<div>
  <div class="book">
    <div class="cover-image">
      <%= image_tag book.cover_image, width: 150, height: 250 %>
    </div>
    <div class="book-details">
      <div class="book-title">
        <%= book.title %>
      </div>
      <div class="book-rating">
        <%= book.average_rating %>
      </div>
      <div class="by_author">
        <%= "by #{book.author.full_name}" %>
      </div>
      <div class="book-summary">
        <%= book.summary %>
      </div>
    </div>
  </div>
</div>

<%= render "reviews", book: book, review_policy: review_policy, reviews: reviews%>

app/views/home/index.html.erb
<div class="left-column">
  <div class="box">
    <h2 class="box-title">What will you discover?</h2>
    <ul class="lastest-books">
      <% books.each do |book| %>
        <li>
          <%= link_to book_path book do %>
            <% image_tag book.cover_image, width: 80, height: 120 %>
          <% end %>
        </li>
      <% end %>
    </ul>
    <div class="box-footer">
    </div>
  </div>
</div>
<div class="right-column">
  <h2>Best Authors</h1>
  <ul class="best-authors">
    <% authors.each do |author| %>
      <li>
        <%= link_to author.full_name, author_path(author) %>
      </li>
    <% end %>
  </ul>
</div>

app/views/layouts/_header.html.erb
<header>
  <div class="wrap">
    <div id="logo">
      <%= link_to root_path do %>
        <%= image_tag "logo.png",width: 64, height: 64 %>
      <% end %>
    </div>
    <ul class="nav-links">
      <li>
        <%= link_to("Books", books_path) %>
      </li>
      <li>
        <%= link_to("Lists", lists_path) %>
      </li>
      <li>
        <%= link_to("Authors", authors_path) %>
      </li>
      <li>
        <% if user_signed_in? %>
          <%= link_to "Logout", session_path, method: :delete %>
        <% else %>
          <%= link_to "Login", new_session_path %>
        <% end %>
      </li>
    </ul>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="ROBOTS" content="NOODP" />
    <meta name="viewport" content="initial-scale=1" />
    <%#
        Configure default and controller-, and view-specific titles in
    config/locales/en.yml. For more see:
      https://github.com/calebthompson/title#usage
    %>
  <title><%= title %></title>
  <%= stylesheet_link_tag :application, media: "all" %>
  <%= csrf_meta_tags %>
  </head>
  <body class="<%= body_class %>">
    <%= render "layouts/header" %>
    <%= render "flashes" -%>
    <div class='content'>
      <%= yield %>
    </div>
    <%= render "javascript" %>
  </body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="ROBOTS" content="NOODP" />
    <meta name="viewport" content="initial-scale=1" />
    <title><%= title %></title>
    <%= stylesheet_link_tag :application, media: "all" %>
    <%= csrf_meta_tags %>
  </head>
  <body class="<%= body_class %>">
    <%= render "layouts/header" %>
    <div class="explore">
      <div class="wrap">
        <div class="text-message">
          <h1>discover what to read next?</h1>
          <p>
          You’re in the right place. Tell us what titles or genres you’ve enjoyed in the past, and we’ll give you surprisingly insightful recommendations.
          </p>
          <%= link_to "Explore Awesome Books", books_path, class: "explore-button" %></button>
        </div>
      </div>
    </div>
    <%= render "flashes" -%>
    <div class='content home'>
      <%= yield %>
    </div>
    <%= render "javascript" %>
  </body>
</html>

app/views/lists/index.html.erb
<% @lists.each do |list| %>
  <div class="list">
    <h1><%= link_to(list.name, list_path(list)) %></h1>
    <ul class="books books-horizontal">
      <%= render partial: "books/book_preview",
        collection: list.ranking_books, as: :book
      %>
  </ul>
  </div>
<% end %>

app/views/lists/show.html.erb
<h1><%= @list.name %></h1>
<ul class="books">
  <%= render @list.books %>
</ul>

app/views/refills/_flashes.html.erb
<div class="flash-success">
  <span>This is a success message <a href="#">with a link</a></span>
</div>

<div class="flash-error">
  <span>This is an error message <a href="#">with a link</a></span>
</div>

<div class="flash-notice">
  <span>This is an notice message <a href="#">with a link</a></span>
</div>

<div class="flash-alert">
  <span>This is an alert message <a href="#">with a link</a></span>
</div>

app/views/refills/_snippet.html.erb
<td class="snippet">
  <div class="copy-source-container">
    <% if language == :javascript -%>
      <a href="javascript:void(0)" class="copy-source">Copy JavaScript</a>
      <a href="javascript:void(0)" class="copy-source copy-coffee">Copy CoffeeScript</a>
    <% elsif language == :markup -%>
      <a href="javascript:void(0)" class="copy-source">Copy HTML</a>
    <% else -%>
      <a href="javascript:void(0)" class="copy-source">Copy Scss</a>
    <% end -%>
  </div>
  <pre><code class="language-<%= language %>"><%== snippet %></code></pre>
</td>